<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */

function feedback_form_form_alter(&$form, $form_state, $form_id) {

  if ($form_id == 'contact_message_feedback_form') {
    $form['actions']['preview']['#access'] = FALSE;
  	$form['actions']['submit']['#value'] = 'Оставить заявку';

    
  	$form['field_email']['widget']['0']['value']['#placeholder'] = 'E-mail';
  	$form['field_email']['widget']['0']['value']['#title'] = FALSE;
  	$form['field_name']['widget']['0']['value']['#placeholder'] = 'Имя';
    $form['field_name']['widget']['0']['value']['#title'] = FALSE;
    $form['field_phone']['widget']['0']['value']['#placeholder'] = 'Телефон';
    $form['field_phone']['widget']['0']['value']['#title'] = FALSE;
  	// $form['subject']['widget']['0']['value']['#placeholder'] = 'Subject';
  	// $form['subject']['widget']['0']['value']['#required'] = 1;
  	// $form['subject']['widget']['0']['value']['#title'] = FALSE;
  	// $form['message']['widget']['0']['value']['#placeholder'] = 'Your Message';
  	// $form['message']['widget']['0']['value']['#required'] = 1;
  	// $form['message']['widget']['0']['value']['#title'] = FALSE;
  }
  
  if ($form_id == 'contact_message_stay_in_touch_form') {
  	$form['actions']['preview']['#access'] = FALSE;
  	$form['actions']['submit']['#value'] = "<img src='/home/user/Загрузки/paper122.png'></img>";
  	$form['field_email']['widget']['0']['value']['#placeholder'] = 'Subscribe our newsletter';
  	$form['field_email']['widget']['0']['value']['#title'] = FALSE;
  }
}



